Task/data binding
radeckid/Marvel_Comics_App pull request #6
Opened 2021-03-05 11:19 UTC by radeckid

Add Data Binding to all fragments

2021-03-05 13:54 UTC, kamiltomczykdv commented on app/src/main/res/layout/activity_main.xml
> +    </data>
Empty data?

2021-03-05 13:55 UTC, kamiltomczykdv commented on app/src/main/res/layout/fragment_favorite.xml
> +    </data>
Empty data?

2021-03-05 13:56 UTC, kamiltomczykdv commented on app/src/main/res/layout/item_loading.xml
> +    </data>
?

2021-03-08 10:18 UTC, piotrgomola requested changes

2021-03-08 10:18 UTC, piotrgomola commented on app/src/main/java/pl/damrad/marvelcomicsapp/adapters/ComicsAdapter.kt
> +        }
It can be done in xml with:

```
<!--Set max char length-->
android:maxLength="150"
<!--Make text view to add ... at the end-->
android:ellipsize="end"
```

2021-03-08 10:18 UTC, piotrgomola commented on app/src/main/java/pl/damrad/marvelcomicsapp/adapters/ComicsAdapter.kt
> +        }
same as above

2021-03-08 10:18 UTC, piotrgomola commented on app/src/main/java/pl/damrad/marvelcomicsapp/fragments/SearchFragment.kt
> +    var binding: FragmentSearchBinding? = null
you can mark binding as lateinit var - as it is expected to have a value, but the initialization is done at a later stage. You already done the second part in an as soon as possible place - onCreateView. 

In that case it doesn't need to be an optional

2021-03-08 10:18 UTC, piotrgomola commented on app/src/main/res/layout/fragment_details.xml
> +                    app:elevation="4dp"
do you have to pass both - andorid:elevation and app:elevation ?

2021-03-08 10:18 UTC, piotrgomola commented on app/src/main/res/layout/fragment_login.xml
> +            app:layout_constraintGuide_percent="0.5" />
nice, you even use guidelines 👌 a question out of curiosity:

Do you mostly use GUI editor for layouts, text editor (xml only) or both sometimes here and sometimes there ?

2021-03-08 10:19 UTC, piotrgomola approved these changes

2021-03-08 10:31 UTC, radeckid commented on app/src/main/res/layout/fragment_login.xml
> +            app:layout_constraintGuide_percent="0.5" />
I almost always use xml but some times i'm looking at GUI editor.

2021-03-08 10:35 UTC, radeckid commented on app/src/main/res/layout/fragment_details.xml
> +                    app:elevation="4dp"
Not really, i need only android:elevation. app:elevation is for Support Library but from ver 21 android:elevation is enough .

2021-03-08 10:46 UTC, kamiltomczykdv approved these changes

2021-03-08 10:47 UTC, merged